services:
  postgres:
    image: postgres:16
    container_name: ig_matrix_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: ig_matrix_synapse
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SYNAPSE_SERVER_NAME: ${SYNAPSE_SERVER_NAME}
      SYNAPSE_REPORT_STATS: ${SYNAPSE_REPORT_STATS}
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8008:8008"
    volumes:
      - ./data/synapse:/data

  mautrix-meta:
    image: dock.mau.dev/mautrix/meta:latest
    container_name: ig_matrix_bridge
    restart: unless-stopped
    depends_on:
      - synapse
    volumes:
      - ./data/mautrix-meta:/data
  
  element:
    image: vectorim/element-web:latest
    container_name: ig_matrix_element
    restart: unless-stopped
    depends_on:
      - synapse
    ports:
      - "8080:80"
    volumes:
      - ./config/element/config.json:/app/config.json:ro